AllCops:
  RunRailsCops: true

Lint/AssignmentInCondition:
  Enabled: false

Lint/HandleExceptions:
  Enabled: false

Lint/UnusedBlockArgument:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Style/AlignHash:
  Enabled: false

Style/AlignParameters:
  Enabled: false

Style/BlockComments:
  Enabled: false

Style/Blocks:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/SingleSpaceBeforeFirstArg:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/TrailingComma:
  Enabled: false
